import type {
  AdminAnalyticsMetric,
  AdminAuditLog,
  AdminBooking,
  AdminHotel,
  AdminModerationAction,
  AdminPartner,
  AdminPayment,
  AdminReport,
  AdminReviewCase,
  AdminRoomSnapshot,
  AdminStatCardProps,
  AdminSystemCheck,
  AdminSystemIndicator,
  AdminUser,
} from "@/types/admin";

export const adminSystemIndicators: AdminSystemIndicator[] = [
  { label: "API", value: "nominal", tone: "blue" },
  { label: "Queue", value: "9m lag", tone: "amber" },
  { label: "Risk", value: "high", tone: "red" },
];

export const adminStats: AdminStatCardProps[] = [
  {
    label: "Total users",
    value: "18,482",
    detail: "642 new this week",
    trend: "+8.2%",
    tone: "blue",
    href: "/admin/users",
  },
  {
    label: "Partner accounts",
    value: "482",
    detail: "42 hotels awaiting review",
    trend: "+3.1%",
    tone: "neutral",
    href: "/admin/partners",
  },
  {
    label: "Pending approvals",
    value: "73",
    detail: "19 over SLA",
    trend: "action required",
    tone: "amber",
    href: "/admin/partners?status=under_review",
  },
  {
    label: "Total bookings",
    value: "94,320",
    detail: "1,206 today",
    trend: "+12.5%",
    tone: "blue",
    href: "/admin/bookings",
  },
  {
    label: "Reports/issues",
    value: "128",
    detail: "11 critical",
    trend: "elevated",
    tone: "red",
    href: "/admin/reports",
  },
  {
    label: "Revenue overview",
    value: "$2.84M",
    detail: "$184K pending payout",
    trend: "+6.7%",
    tone: "neutral",
    href: "/admin/payments",
  },
];

export const adminUsers: AdminUser[] = [
  {
    id: "u-1001",
    name: "Maya Chen",
    email: "maya.chen@example.com",
    role: "client",
    status: "active",
    joinedAt: "2026-01-14",
    lastActive: "8 min ago",
    bookings: 12,
    reports: 0,
    riskScore: 8,
  },
  {
    id: "u-1002",
    name: "Orchid Stays Ops",
    email: "ops@orchidstays.example",
    role: "partner",
    status: "under_review",
    joinedAt: "2025-11-02",
    lastActive: "22 min ago",
    bookings: 184,
    reports: 3,
    riskScore: 64,
  },
  {
    id: "u-1003",
    name: "Jonas Reed",
    email: "jonas.reed@example.com",
    role: "client",
    status: "suspended",
    joinedAt: "2025-08-19",
    lastActive: "2 days ago",
    bookings: 6,
    reports: 5,
    riskScore: 91,
  },
  {
    id: "u-1004",
    name: "Northline Hotels",
    email: "admin@northline.example",
    role: "partner",
    status: "active",
    joinedAt: "2025-05-07",
    lastActive: "1 hour ago",
    bookings: 433,
    reports: 1,
    riskScore: 22,
  },
  {
    id: "u-1005",
    name: "Ari Patel",
    email: "ari.patel@example.com",
    role: "client",
    status: "under_review",
    joinedAt: "2026-03-28",
    lastActive: "14 min ago",
    bookings: 2,
    reports: 2,
    riskScore: 58,
  },
  {
    id: "u-9001",
    name: "Internal Admin",
    email: "admin@bookyourstay.example",
    role: "admin",
    status: "active",
    joinedAt: "2025-01-01",
    lastActive: "now",
    bookings: 0,
    reports: 0,
    riskScore: 2,
  },
];

export const adminPartners: AdminPartner[] = [
  {
    id: "u-1002",
    companyName: "Orchid Stays Ops",
    contactName: "Nara Sutham",
    email: "ops@orchidstays.example",
    status: "under_review",
    verificationStatus: "pending",
    payoutStatus: "held",
    joinedAt: "2025-11-02",
    lastActive: "22 min ago",
    riskScore: 64,
    notes: "Requires document verification before new hotels can publish.",
  },
  {
    id: "u-1004",
    companyName: "Northline Hotels",
    contactName: "Evan Brooks",
    email: "admin@northline.example",
    status: "active",
    verificationStatus: "approved",
    payoutStatus: "clear",
    joinedAt: "2025-05-07",
    lastActive: "1 hour ago",
    riskScore: 22,
    notes: "Established partner with mixed hotel-level moderation signals.",
  },
];

export const adminHotels: AdminHotel[] = [
  {
    id: "h-3001",
    name: "Metro Axis Hotel",
    city: "Bangkok",
    ownerId: "u-1002",
    ownerName: "Orchid Stays Ops",
    approvalStatus: "pending",
    reviewScore: "4.2",
    flags: 4,
    rooms: 86,
    bookings: 231,
    payoutStatus: "held",
  },
  {
    id: "h-3002",
    name: "Northline Central",
    city: "Chicago",
    ownerId: "u-1004",
    ownerName: "Northline Hotels",
    approvalStatus: "approved",
    reviewScore: "4.7",
    flags: 1,
    rooms: 142,
    bookings: 840,
    payoutStatus: "clear",
  },
  {
    id: "h-3003",
    name: "Harbor Grid Suites",
    city: "Seattle",
    ownerId: "u-1004",
    ownerName: "Northline Hotels",
    approvalStatus: "flagged",
    reviewScore: "3.8",
    flags: 8,
    rooms: 64,
    bookings: 118,
    payoutStatus: "review",
  },
  {
    id: "h-3004",
    name: "Civic Square Rooms",
    city: "Austin",
    ownerId: "u-1002",
    ownerName: "Orchid Stays Ops",
    approvalStatus: "suspended",
    reviewScore: "3.1",
    flags: 13,
    rooms: 38,
    bookings: 74,
    payoutStatus: "blocked",
  },
  {
    id: "h-3005",
    name: "East Dock Residence",
    city: "Boston",
    ownerId: "u-1004",
    ownerName: "Northline Hotels",
    approvalStatus: "approved",
    reviewScore: "4.5",
    flags: 0,
    rooms: 51,
    bookings: 302,
    payoutStatus: "clear",
  },
];

export const adminBookings: AdminBooking[] = [
  {
    id: "b-7001",
    userId: "u-1001",
    guestName: "Maya Chen",
    hotelId: "h-3002",
    hotelName: "Northline Central",
    dates: "May 20-23, 2026",
    status: "confirmed",
    paymentStatus: "paid",
    amount: "$642.00",
    disputeStatus: "none",
    riskSignal: "normal",
  },
  {
    id: "b-7002",
    userId: "u-1003",
    guestName: "Jonas Reed",
    hotelId: "h-3004",
    hotelName: "Civic Square Rooms",
    dates: "May 18-19, 2026",
    status: "cancelled",
    paymentStatus: "disputed",
    amount: "$188.00",
    disputeStatus: "chargeback open",
    riskSignal: "velocity spike",
  },
  {
    id: "b-7003",
    userId: "u-1005",
    guestName: "Ari Patel",
    hotelId: "h-3001",
    hotelName: "Metro Axis Hotel",
    dates: "May 28-30, 2026",
    status: "pending",
    paymentStatus: "failed",
    amount: "$420.00",
    disputeStatus: "none",
    riskSignal: "card retries",
  },
  {
    id: "b-7004",
    userId: "u-1001",
    guestName: "Maya Chen",
    hotelId: "h-3005",
    hotelName: "East Dock Residence",
    dates: "Jun 01-04, 2026",
    status: "confirmed",
    paymentStatus: "paid",
    amount: "$812.00",
    disputeStatus: "none",
    riskSignal: "normal",
  },
  {
    id: "b-7005",
    userId: "u-1005",
    guestName: "Ari Patel",
    hotelId: "h-3003",
    hotelName: "Harbor Grid Suites",
    dates: "Jun 08-09, 2026",
    status: "review",
    paymentStatus: "pending",
    amount: "$238.00",
    disputeStatus: "manual review",
    riskSignal: "device mismatch",
  },
];

export const adminReviews: AdminReviewCase[] = [
  {
    id: "r-5001",
    userId: "u-1003",
    userName: "Jonas Reed",
    hotelId: "h-3004",
    hotelName: "Civic Square Rooms",
    rating: 1,
    status: "reported",
    reportCount: 6,
    excerpt: "Unsafe listing details and a host who asked to move payment off-platform.",
    createdAt: "2026-05-14",
  },
  {
    id: "r-5002",
    userId: "u-1001",
    userName: "Maya Chen",
    hotelId: "h-3002",
    hotelName: "Northline Central",
    rating: 5,
    status: "pending",
    reportCount: 0,
    excerpt: "Clean, efficient check-in, and clear room photos.",
    createdAt: "2026-05-12",
  },
  {
    id: "r-5003",
    userId: "u-1005",
    userName: "Ari Patel",
    hotelId: "h-3003",
    hotelName: "Harbor Grid Suites",
    rating: 2,
    status: "low_rating",
    reportCount: 1,
    excerpt: "Room inventory changed after payment and support did not respond.",
    createdAt: "2026-05-11",
  },
  {
    id: "r-5004",
    userId: "u-1003",
    userName: "Jonas Reed",
    hotelId: "h-3001",
    hotelName: "Metro Axis Hotel",
    rating: 1,
    status: "hidden",
    reportCount: 4,
    excerpt: "Contains personal contact information and repeated policy violations.",
    createdAt: "2026-05-09",
  },
];

export const adminReports: AdminReport[] = [
  {
    id: "rep-9001",
    type: "hotel",
    subjectId: "h-3004",
    subjectLabel: "Civic Square Rooms",
    severity: "critical",
    status: "escalated",
    reason: "Off-platform payment solicitation",
    createdAt: "2026-05-15 08:42",
    assignedTo: "Trust Ops",
  },
  {
    id: "rep-9002",
    type: "user",
    subjectId: "u-1003",
    subjectLabel: "Jonas Reed",
    severity: "high",
    status: "open",
    reason: "Chargeback pattern across bookings",
    createdAt: "2026-05-15 11:08",
    assignedTo: "Risk Review",
  },
  {
    id: "rep-9003",
    type: "review",
    subjectId: "r-5001",
    subjectLabel: "Review r-5001",
    severity: "medium",
    status: "triaged",
    reason: "Reported by hotel owner",
    createdAt: "2026-05-14 16:20",
    assignedTo: "Content",
  },
  {
    id: "rep-9004",
    type: "hotel",
    subjectId: "h-3003",
    subjectLabel: "Harbor Grid Suites",
    severity: "high",
    status: "open",
    reason: "Room availability mismatch",
    createdAt: "2026-05-13 09:11",
    assignedTo: "Listings",
  },
];

export const adminPayments: AdminPayment[] = [
  {
    id: "pay-8001",
    bookingId: "b-7001",
    hotelId: "h-3002",
    partnerName: "Northline Hotels",
    amount: "$642.00",
    status: "paid",
    type: "charge",
    createdAt: "2026-05-10 14:38",
    risk: "normal",
  },
  {
    id: "pay-8002",
    bookingId: "b-7002",
    hotelId: "h-3004",
    partnerName: "Orchid Stays Ops",
    amount: "$188.00",
    status: "disputed",
    type: "dispute",
    createdAt: "2026-05-13 18:04",
    risk: "chargeback",
  },
  {
    id: "pay-8003",
    bookingId: "b-7003",
    hotelId: "h-3001",
    partnerName: "Orchid Stays Ops",
    amount: "$420.00",
    status: "failed",
    type: "charge",
    createdAt: "2026-05-14 10:12",
    risk: "retry loop",
  },
  {
    id: "pay-8004",
    bookingId: "b-7004",
    hotelId: "h-3005",
    partnerName: "Northline Hotels",
    amount: "$812.00",
    status: "pending",
    type: "payout",
    createdAt: "2026-05-16 05:30",
    risk: "payout queue",
  },
];

export const adminAnalyticsMetrics: AdminAnalyticsMetric[] = [
  {
    title: "Growth",
    value: "+18.4%",
    caption: "30-day active accounts",
    tone: "blue",
    bars: [42, 48, 53, 59, 63, 71, 78],
  },
  {
    title: "Bookings",
    value: "8,420",
    caption: "rolling 30 days",
    tone: "neutral",
    bars: [64, 58, 72, 81, 76, 84, 88],
  },
  {
    title: "Revenue",
    value: "$612K",
    caption: "net processed",
    tone: "blue",
    bars: [50, 56, 62, 60, 69, 80, 86],
  },
  {
    title: "Cancellations",
    value: "7.8%",
    caption: "2.1 points above baseline",
    tone: "amber",
    bars: [28, 34, 31, 42, 48, 52, 57],
  },
];

export const adminSystemChecks: AdminSystemCheck[] = [
  {
    name: "Application runtime",
    status: "operational",
    detail: "Next.js routes responding within target latency",
    updatedAt: "1 min ago",
    tone: "blue",
  },
  {
    name: "Email provider",
    status: "degraded",
    detail: "Passwordless and booking email backlog detected",
    updatedAt: "9 min ago",
    tone: "amber",
  },
  {
    name: "Moderation queue",
    status: "elevated",
    detail: "Critical reports above normal threshold",
    updatedAt: "3 min ago",
    tone: "red",
  },
  {
    name: "Object storage",
    status: "stable",
    detail: "Hotel media upload pipeline is healthy",
    updatedAt: "12 min ago",
    tone: "neutral",
  },
];

export const adminAuditLogs: AdminAuditLog[] = [
  {
    id: "audit-1",
    actor: "Trust Ops",
    action: "Suspended hotel",
    target: "Civic Square Rooms",
    timestamp: "2026-05-16 09:44",
    severity: "critical",
  },
  {
    id: "audit-2",
    actor: "Risk Review",
    action: "Opened payment dispute",
    target: "Booking b-7002",
    timestamp: "2026-05-16 08:16",
    severity: "high",
  },
  {
    id: "audit-3",
    actor: "Content",
    action: "Hidden review",
    target: "Review r-5004",
    timestamp: "2026-05-15 18:02",
    severity: "medium",
  },
];

export const adminModerationActions: AdminModerationAction[] = [
  {
    id: "mod-1",
    actor: "Trust Ops",
    action: "Escalated report",
    target: "rep-9001",
    time: "11 min ago",
    outcome: "Awaiting partner response",
  },
  {
    id: "mod-2",
    actor: "Listings",
    action: "Rejected room update",
    target: "Harbor Grid Suites",
    time: "28 min ago",
    outcome: "Incorrect inventory evidence",
  },
  {
    id: "mod-3",
    actor: "Risk Review",
    action: "Restricted account",
    target: "Jonas Reed",
    time: "1 hour ago",
    outcome: "Manual review required",
  },
];

export const adminRoomSnapshots: AdminRoomSnapshot[] = [
  {
    id: "room-1",
    hotelId: "h-3001",
    name: "Compact Queen",
    status: "pending",
    nightlyRate: "$140",
    occupancy: "61%",
    flags: 2,
  },
  {
    id: "room-2",
    hotelId: "h-3002",
    name: "Executive King",
    status: "approved",
    nightlyRate: "$214",
    occupancy: "88%",
    flags: 0,
  },
  {
    id: "room-3",
    hotelId: "h-3003",
    name: "Waterfront Double",
    status: "flagged",
    nightlyRate: "$238",
    occupancy: "47%",
    flags: 4,
  },
  {
    id: "room-4",
    hotelId: "h-3004",
    name: "City Studio",
    status: "suspended",
    nightlyRate: "$94",
    occupancy: "12%",
    flags: 7,
  },
];

export function getAdminHotelById(hotelId: string) {
  return adminHotels.find((hotel) => hotel.id === hotelId);
}

export function getAdminPartnerById(partnerId: string) {
  return adminPartners.find((partner) => partner.id === partnerId);
}

export function getAdminPartnerForHotel(hotelId: string) {
  const hotel = getAdminHotelById(hotelId);
  if (!hotel) return undefined;

  return getAdminPartnerById(hotel.ownerId);
}

export function getAdminHotelsForPartner(partnerId: string) {
  return adminHotels.filter((hotel) => hotel.ownerId === partnerId);
}

export function partnerHotelHref(hotelId: string) {
  const partner = getAdminPartnerForHotel(hotelId);
  if (!partner) return "/admin/partners";

  return `/admin/partners/${partner.id}?hotel=${hotelId}`;
}
