import type {
  PartnerAnalyticsMetric,
  PartnerBooking,
  PartnerCalendarRow,
  PartnerHotel,
  PartnerNotification,
  PartnerQuickAction,
  PartnerReview,
  PartnerRoom,
  PartnerStat,
} from "@/types/partner";

export const partnerStats: PartnerStat[] = [
  {
    label: "Total bookings",
    value: "1,284",
    detail: "186 this month",
    trend: "+12.4%",
    tone: "indigo",
  },
  {
    label: "Revenue",
    value: "$482.6K",
    detail: "net confirmed revenue",
    trend: "+8.1%",
    tone: "emerald",
  },
  {
    label: "Active listings",
    value: "18",
    detail: "3 awaiting review",
    trend: "+2",
    tone: "slate",
  },
  {
    label: "Average rating",
    value: "4.82",
    detail: "across 428 reviews",
    trend: "+0.06",
    tone: "amber",
  },
  {
    label: "Pending check-ins",
    value: "34",
    detail: "next 72 hours",
    trend: "5 urgent",
    tone: "rose",
  },
];

export const partnerQuickActions: PartnerQuickAction[] = [
  {
    label: "Add hotel",
    description: "Create a new listing draft",
    href: "/partner/hotels/new",
  },
  {
    label: "Review calendar",
    description: "Check room availability",
    href: "/partner/calendar",
  },
  {
    label: "Open bookings",
    description: "Confirm upcoming arrivals",
    href: "/partner/bookings",
  },
  {
    label: "Reply to reviews",
    description: "Answer recent guest feedback",
    href: "/partner/reviews",
  },
];

export const partnerHotels: PartnerHotel[] = [
  {
    id: "grand-orchid",
    name: "Grand Orchid Residences",
    city: "Bangkok",
    address: "12 Wireless Road, Lumphini",
    status: "Active",
    rating: "4.9",
    rooms: 84,
    occupancy: "87%",
    revenue: "$128.4K",
    amenities: ["Sky pool", "Business lounge", "Airport transfer"],
    policySummary: "Flexible cancellation until 48 hours before arrival.",
    payoutStatus: "Weekly payout active",
    checkIn: "14:00",
    checkOut: "11:00",
  },
  {
    id: "harbor-view",
    name: "Harbor View Suites",
    city: "Singapore",
    address: "4 Marina Boulevard",
    status: "Active",
    rating: "4.7",
    rooms: 52,
    occupancy: "79%",
    revenue: "$96.2K",
    amenities: ["Club floor", "Meeting rooms", "Late checkout"],
    policySummary: "Standard cancellation with prepaid rate options.",
    payoutStatus: "Monthly payout active",
    checkIn: "15:00",
    checkOut: "12:00",
  },
  {
    id: "emerald-bay",
    name: "Emerald Bay Retreat",
    city: "Phuket",
    address: "88 Cape Panwa Road",
    status: "Draft",
    rating: "New",
    rooms: 26,
    occupancy: "Preview",
    revenue: "$0",
    amenities: ["Private beach", "Spa", "Villa dining"],
    policySummary: "Policies pending partner review.",
    payoutStatus: "Payout setup required",
    checkIn: "14:00",
    checkOut: "11:00",
  },
];

export const partnerRooms: PartnerRoom[] = [
  {
    id: "orchid-executive",
    hotelId: "grand-orchid",
    name: "Executive King Suite",
    type: "Suite",
    rate: "$248",
    occupancy: "92%",
    status: "Available",
    capacity: "2 adults",
    size: "48 sqm",
    beds: "1 king bed",
    imageCount: 12,
  },
  {
    id: "orchid-deluxe",
    hotelId: "grand-orchid",
    name: "Deluxe City Room",
    type: "Double",
    rate: "$164",
    occupancy: "84%",
    status: "Limited",
    capacity: "2 adults",
    size: "32 sqm",
    beds: "1 queen bed",
    imageCount: 8,
  },
  {
    id: "harbor-premier",
    hotelId: "harbor-view",
    name: "Premier Harbor Room",
    type: "King",
    rate: "$302",
    occupancy: "76%",
    status: "Available",
    capacity: "2 adults",
    size: "38 sqm",
    beds: "1 king bed",
    imageCount: 10,
  },
  {
    id: "harbor-club",
    hotelId: "harbor-view",
    name: "Club Corner Suite",
    type: "Suite",
    rate: "$421",
    occupancy: "68%",
    status: "Available",
    capacity: "3 guests",
    size: "55 sqm",
    beds: "1 king bed and sofa",
    imageCount: 14,
  },
  {
    id: "emerald-villa",
    hotelId: "emerald-bay",
    name: "Bayfront Villa",
    type: "Villa",
    rate: "$520",
    occupancy: "Draft",
    status: "Disabled",
    capacity: "4 guests",
    size: "92 sqm",
    beds: "2 king beds",
    imageCount: 6,
  },
];

export const partnerBookings: PartnerBooking[] = [
  {
    id: "bk-1048",
    guest: "Maya Chen",
    guestEmail: "maya.chen@example.com",
    guestPhone: "+65 8123 4401",
    hotelId: "grand-orchid",
    hotel: "Grand Orchid Residences",
    room: "Executive King Suite",
    dates: "May 18-22, 2026",
    payment: "$992",
    paymentStatus: "Paid",
    status: "Upcoming",
    total: "$992.00",
    checkInTime: "18 May, 14:00",
    notes: "Guest requested a quiet floor and airport transfer details.",
  },
  {
    id: "bk-1047",
    guest: "Adrian Blake",
    guestEmail: "adrian.blake@example.com",
    guestPhone: "+44 7700 900311",
    hotelId: "harbor-view",
    hotel: "Harbor View Suites",
    room: "Premier Harbor Room",
    dates: "May 20-24, 2026",
    payment: "$1,208",
    paymentStatus: "Pending",
    status: "Upcoming",
    total: "$1,208.00",
    checkInTime: "20 May, 15:00",
    notes: "Corporate rate. Invoice details should be confirmed at desk.",
  },
  {
    id: "bk-1041",
    guest: "Nora Williams",
    guestEmail: "nora.williams@example.com",
    guestPhone: "+1 415 555 0188",
    hotelId: "grand-orchid",
    hotel: "Grand Orchid Residences",
    room: "Deluxe City Room",
    dates: "May 10-12, 2026",
    payment: "$328",
    paymentStatus: "Paid",
    status: "Completed",
    total: "$328.00",
    checkInTime: "10 May, 14:00",
    notes: "Completed stay. Review invitation sent.",
  },
  {
    id: "bk-1038",
    guest: "Jonas Weber",
    guestEmail: "jonas.weber@example.com",
    guestPhone: "+49 151 5555 0191",
    hotelId: "harbor-view",
    hotel: "Harbor View Suites",
    room: "Club Corner Suite",
    dates: "May 8-11, 2026",
    payment: "$0",
    paymentStatus: "Refunded",
    status: "Cancelled",
    total: "$1,263.00",
    checkInTime: "Cancelled",
    notes: "Guest cancelled within the free cancellation window.",
  },
];

export const partnerReviews: PartnerReview[] = [
  {
    id: "rv-441",
    guest: "Nora Williams",
    hotel: "Grand Orchid Residences",
    rating: 5,
    date: "May 13, 2026",
    comment:
      "Excellent service and a very efficient check-in. The lounge team handled our meeting setup perfectly.",
    status: "Unanswered",
  },
  {
    id: "rv-438",
    guest: "Liam Carter",
    hotel: "Harbor View Suites",
    rating: 3,
    date: "May 12, 2026",
    comment:
      "Room was clean, but breakfast service was slow during peak hours. The view was exceptional.",
    status: "Unanswered",
  },
  {
    id: "rv-431",
    guest: "Priya Raman",
    hotel: "Grand Orchid Residences",
    rating: 4,
    date: "May 9, 2026",
    comment:
      "Comfortable room and helpful concierge. I would like clearer instructions for late arrivals.",
    status: "Replied",
  },
];

export const partnerAnalyticsMetrics: PartnerAnalyticsMetric[] = [
  {
    title: "Bookings/month",
    value: "186",
    caption: "May forecast",
    bars: [45, 58, 62, 74, 68, 86, 91],
  },
  {
    title: "Revenue/month",
    value: "$84.2K",
    caption: "confirmed gross",
    bars: [38, 42, 55, 61, 78, 83, 96],
  },
  {
    title: "Occupancy",
    value: "82%",
    caption: "portfolio average",
    bars: [70, 76, 81, 84, 79, 88, 82],
  },
  {
    title: "Top hotel",
    value: "Grand Orchid",
    caption: "$128.4K trailing 30 days",
    bars: [54, 59, 68, 78, 83, 86, 94],
  },
  {
    title: "Cancellation rate",
    value: "4.8%",
    caption: "down 1.1 points",
    bars: [74, 68, 61, 55, 52, 49, 44],
  },
  {
    title: "Average rating",
    value: "4.82",
    caption: "428 published reviews",
    bars: [80, 82, 79, 84, 86, 88, 91],
  },
];

export const partnerCalendarDates = [
  "May 18",
  "May 19",
  "May 20",
  "May 21",
  "May 22",
  "May 23",
  "May 24",
];

export const partnerCalendarRows: PartnerCalendarRow[] = [
  {
    room: "Executive King Suite",
    hotel: "Grand Orchid",
    blocks: [
      { start: 1, span: 3, label: "Maya C.", tone: "emerald" },
      { start: 5, span: 2, label: "Held", tone: "amber" },
    ],
  },
  {
    room: "Deluxe City Room",
    hotel: "Grand Orchid",
    blocks: [{ start: 2, span: 2, label: "Open", tone: "indigo" }],
  },
  {
    room: "Premier Harbor Room",
    hotel: "Harbor View",
    blocks: [{ start: 3, span: 4, label: "Adrian B.", tone: "emerald" }],
  },
  {
    room: "Club Corner Suite",
    hotel: "Harbor View",
    blocks: [{ start: 0, span: 2, label: "Maintenance", tone: "rose" }],
  },
];

export const partnerNotifications: PartnerNotification[] = [
  {
    id: "nt-901",
    type: "New booking",
    title: "Maya Chen booked Executive King Suite",
    detail: "Grand Orchid Residences, May 18-22",
    time: "12 minutes ago",
    href: "/partner/bookings/bk-1048",
    tone: "emerald",
  },
  {
    id: "nt-900",
    type: "Cancellation",
    title: "Jonas Weber cancelled a Club Corner Suite stay",
    detail: "Refund marked as completed",
    time: "2 hours ago",
    href: "/partner/bookings/bk-1038",
    tone: "rose",
  },
  {
    id: "nt-899",
    type: "New review",
    title: "New 3-star review needs attention",
    detail: "Harbor View Suites breakfast service feedback",
    time: "6 hours ago",
    href: "/partner/reviews",
    tone: "amber",
  },
  {
    id: "nt-898",
    type: "Payout",
    title: "Weekly payout is scheduled",
    detail: "$18,420 arrives on May 20",
    time: "Yesterday",
    href: "/partner/settings",
    tone: "indigo",
  },
];
